# Generated by Django 2.1.2 on 2018-12-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
    ]
